// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleWeb.Data;

#nullable disable

namespace ScheduleWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331200920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ScheduleWeb.Models.Audience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Audiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            IsDeleted = 0,
                            Number = "26",
                            Type = "Комп'ютерний клас"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            IsDeleted = 0,
                            Number = "с/з",
                            Type = "Спортзал"
                        });
                });

            modelBuilder.Entity("ScheduleWeb.Models.BellSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsShortened")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BellSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = "09:50",
                            IsShortened = 0,
                            LessonNumber = 1,
                            StartTime = "08:30"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = "11:20",
                            IsShortened = 0,
                            LessonNumber = 2,
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = "13:10",
                            IsShortened = 0,
                            LessonNumber = 3,
                            StartTime = "11:50"
                        });
                });

            modelBuilder.Entity("ScheduleWeb.Models.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("ScheduleWeb.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = 1,
                            IsDeleted = 0,
                            Name = "ІПЗ-1/1",
                            Shift = 1,
                            Specialty = "Інженерія ПЗ"
                        },
                        new
                        {
                            Id = 2,
                            Course = 1,
                            IsDeleted = 0,
                            Name = "ІПЗ-1/2",
                            Shift = 1,
                            Specialty = "Інженерія ПЗ"
                        },
                        new
                        {
                            Id = 3,
                            Course = 1,
                            IsDeleted = 0,
                            Name = "КН-1/1",
                            Shift = 1,
                            Specialty = "Комп'ютерні науки"
                        },
                        new
                        {
                            Id = 4,
                            Course = 4,
                            IsDeleted = 0,
                            Name = "ІПЗ-4/1",
                            Shift = 1,
                            Specialty = "Інженерія ПЗ"
                        });
                });

            modelBuilder.Entity("ScheduleWeb.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Адміністратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Викладач"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Студент"
                        });
                });

            modelBuilder.Entity("ScheduleWeb.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudienceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("AudienceId", "Date", "LessonNumber")
                        .IsUnique();

                    b.HasIndex("GroupId", "Date", "LessonNumber")
                        .IsUnique();

                    b.HasIndex("TeacherId", "Date", "LessonNumber")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ScheduleWeb.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubjectEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = 0,
                            MaxPerDay = 2,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = 0,
                            MaxPerDay = 2,
                            Name = "Програмування"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = 0,
                            MaxPerDay = 1,
                            Name = "Історія України"
                        });
                });

            modelBuilder.Entity("ScheduleWeb.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ScheduleWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScheduleWeb.Models.Curriculum", b =>
                {
                    b.HasOne("ScheduleWeb.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleWeb.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ScheduleWeb.Models.Schedule", b =>
                {
                    b.HasOne("ScheduleWeb.Models.Audience", "Audience")
                        .WithMany()
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleWeb.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleWeb.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleWeb.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audience");

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ScheduleWeb.Models.User", b =>
                {
                    b.HasOne("ScheduleWeb.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
